### ISSUE TITLE
CSS from VIP not included in Quickstart

### ISSUE THREAD

**Issue by zrothauser** [Automattic/vip-quickstart#435]
I recently fixed an issue on a VIP site that was caused by a conflict between these styles and the theme styles. It seems that Quickstart doesn't include these, but they are included in the concatenated CSS on all VIP sites. I wasn't able to replicate the issue locally while testing since these were only included on the live site. Could this CSS be added to Quickstart if it's going to remain on VIP? 

```css
/*
        Global styles for WordPress.com
*/
img.latex {
        border: none;
        vertical-align: middle;
}
.video-player {
        border: 0;
        margin: auto;
        padding: 5px;
        text-align: center;
        max-width: 100%;
}
.hidden {
        display: none;
}
.screen-reader-text {
        position: absolute;
        left: -1000em;
}
.comment object,
.comment embed,
.embed-vimeo iframe,
.embed-youtube iframe {
        max-width: 100%; /* avoid videos being too wide */
}
```
